# Copyright 2018 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    check:
      jobs:
        - openstack-tox-lower-constraints
        - kuryr-kubernetes-tempest-octavia
        - kuryr-kubernetes-tempest-daemon-octavia
        - kuryr-kubernetes-tempest-daemon-openshift-octavia
        - kuryr-kubernetes-tempest-lbaasv2
        - kuryr-kubernetes-tempest-daemon-lbaasv2
        - kuryr-kubernetes-tempest-daemon-openshift-lbaasv2
        - kuryr-kubernetes-tempest-daemon-containerized-octavia
        - kuryr-kubernetes-tempest-dragonflow
        - kuryr-kubernetes-tempest-daemon-containerized-ovn
    gate:
      jobs:
        - openstack-tox-lower-constraints
        - kuryr-kubernetes-tempest-octavia
        - kuryr-kubernetes-tempest-daemon-octavia
        - kuryr-kubernetes-tempest-lbaasv2
        - kuryr-kubernetes-tempest-daemon-lbaasv2
        - kuryr-kubernetes-tempest-daemon-containerized-octavia
    experimental:
      jobs:
        - kuryr-kubernetes-tempest-multinode-octavia
        - kuryr-kubernetes-tempest-multinode-lbaasv2
        - kuryr-kubernetes-tempest-octavia-centos-7
        - kuryr-kubernetes-tempest-lbaasv2-centos-7
        - kuryr-kubernetes-tempest-containerized-lbaasv2
        - kuryr-kubernetes-tempest-daemon-containerized-openshift-lbaasv2
        - kuryr-kubernetes-tempest-daemon-pools-lbaasv2
        - kuryr-kubernetes-tempest-daemon-containerized-lbaasv2
        - kuryr-kubernetes-tempest-daemon-containerized-octavia-l2
        - kuryr-kubernetes-tempest-daemon-containerized-octavia-namespace
        - kuryr-kubernetes-tempest-daemon-ovn

- nodeset:
    name: openstack-centos-7-single-node
    nodes:
      - name: controller
        label: centos-7
    groups:
      - name: tempest
        nodes:
          - controller

- job:
    name: kuryr-kubernetes-tempest-base
    parent: devstack-tempest
    description: Base kuryr-kubernetes-job
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/devstack-plugin-container
      - openstack/kuryr
      - openstack/kuryr-kubernetes
      - openstack/kuryr-tempest-plugin
      - openstack/neutron-lbaas
      - openstack/tempest
    post-run: playbooks/copy-k8s-logs.yaml
    host-vars:
      controller:
        devstack_plugins:
          kuryr-kubernetes: https://git.openstack.org/openstack/kuryr
          devstack-plugin-container: https://git.openstack.org/openstack/devstack-plugin-container
    vars:
      tempest_test_regex: '^(kuryr_tempest_plugin.tests.)'
      tox_envlist: 'all'
      devstack_localrc:
        KURYR_K8S_API_PORT: 8080
        TEMPEST_PLUGINS: '/opt/stack/kuryr-tempest-plugin'
      devstack_services:
        # TODO(dmellado):Temporary workaround until proper fix
        base: false
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
        tempest: true
        neutron: true
        q-agt: true
        q-dhcp: true
        q-l3: true
        q-svc: true
        q-meta: true
        key: true
        mysql: true
        rabbit: true
        n-api: true
        n-api-meta: true
        n-cpu: true
        n-cond: true
        n-sch: true
        placement-api: true
        placement-client: true
        g-api: true
        g-reg: true
        etcd3: true
        kubernetes-api: true
        kubernetes-controller-manager: true
        kubernetes-scheduler: true
        kubelet: true
        kuryr-kubernetes: true
      zuul_copy_output:
        '{{ devstack_log_dir }}/kubernetes': 'logs'
    irrelevant-files:
      - ^.*\.rst$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^contrib/.*$

- job:
    name: kuryr-kubernetes-tempest-daemon-pools-lbaasv2
    parent: kuryr-kubernetes-tempest-daemon-lbaasv2
    description: |
      Kuryr-Kubernetes tempest job using port-pool feature
    vars:
      tempest_test_regex: '^(kuryr_tempest_plugin.tests.scenario.test_port_pool.TestPortPoolScenario.test_port_pool)'
      devstack_localrc:
        KURYR_USE_PORT_POOLS: true
        KURYR_POD_VIF_DRIVER: neutron-vif
        KURYR_VIF_POOL_DRIVER: neutron
        TEMPEST_CONCURRENCY: 1

- job:
    name: kuryr-kubernetes-tempest-octavia
    parent: kuryr-kubernetes-tempest-base
    description: |
      Kuryr-Kubernetes tempest job using octavia
    required-projects:
      - openstack/barbican
      - openstack/octavia
      - openstack/python-barbicanclient
      - openstack/python-octaviaclient
    pre-run: playbooks/get_amphora_tarball.yaml
    host-vars:
      controller:
        devstack_plugins:
          octavia: https://git.openstack.org/openstack/octavia
          barbican: https://git.openstack.org/openstack/barbican
    vars:
      devstack_localrc:
        OCTAVIA_AMP_IMAGE_FILE: "/tmp/test-only-amphora-x64-haproxy-ubuntu-xenial.qcow2"
        OCTAVIA_AMP_IMAGE_SIZE: 3
        OCTAVIA_AMP_IMAGE_NAME: "test-only-amphora-x64-haproxy-ubuntu-xenial"
      devstack_local_conf:
        post-config:
          $OCTAVIA_CONF:
            controller_worker:
              amp_active_retries: 9999
      devstack_services:
        octavia: true
        o-api: true
        o-cw: true
        o-hk: true
        o-hm: true

- job:
    name: kuryr-kubernetes-tempest-octavia-centos-7
    parent: kuryr-kubernetes-tempest-octavia
    nodeset: openstack-centos-7-single-node
    voting: false

- job:
    name: kuryr-kubernetes-tempest-daemon-octavia
    parent: kuryr-kubernetes-tempest-octavia
    description: |
        Kuryr-Kubernetes tempest job using octavia and CNI daemon
    vars:
      devstack_services:
        kuryr-daemon: true

- job:
    name: kuryr-kubernetes-tempest-daemon-containerized-octavia
    parent: kuryr-kubernetes-tempest-daemon-octavia
    description: |
        Kuryr-Kubernetes tempest job using octavia, kuryr containerized and CNI daemon
    vars:
      devstack_localrc:
        KURYR_K8S_CONTAINERIZED_DEPLOYMENT: true

- job:
    name: kuryr-kubernetes-tempest-daemon-containerized-octavia-l2
    parent: kuryr-kubernetes-tempest-daemon-containerized-octavia
    description: |
        Kuryr-Kubernetes tempest job using octavia in l2 mode, kuryr containerized and CNI daemon
    vars:
      devstack_localrc:
        KURYR_K8S_OCTAVIA_MEMBER_MODE: L2

- job:
    name: kuryr-kubernetes-tempest-openshift-octavia
    parent: kuryr-kubernetes-tempest-octavia
    description: |
      Kuryr-Kubernetes tempest job using octavia and OpenShift
    vars:
      devstack_localrc:
        DOCKER_CGROUP_DRIVER: "systemd"
      devstack_services:
        kubernetes-api: false
        kubernetes-controller-manager: false
        kubernetes-scheduler: false
        kubelet: false
        openshift-master: true
        openshift-node: true

- job:
    name: kuryr-kubernetes-tempest-daemon-openshift-octavia
    parent: kuryr-kubernetes-tempest-openshift-octavia
    description: |
      Kuryr-Kubernetes tempest job using octavia, CNI daemon and OpenShift
    vars:
      devstack_services:
        kuryr-daemon: true
    voting: false

- job:
    name: kuryr-kubernetes-tempest-multinode-octavia
    parent: kuryr-kubernetes-tempest-octavia
    description: |
        Kuryr-Kubernetes tempest multinode job using octavia
    nodeset: openstack-two-node
    host-vars:
      controller:
        devstack_plugins:
          barbican: https://git.openstack.org/openstack/barbican
          devstack-plugin-container: https://git.openstack.org/openstack/devstack-plugin-container
          kuryr-kubernetes: https://git.openstack.org/openstack/kuryr
          octavia: https://git.openstack.org/openstack/octavia
    group-vars:
      subnode:
        devstack_services:
          tls-proxy: false
          c-vol: false
          c-bak: false
    vars:
      devstack_services:
        tls-proxy: false
    voting: false

- job:
    name: kuryr-kubernetes-tempest-lbaasv2
    parent: kuryr-kubernetes-tempest-base
    description: |
      Kuryr-Kubernetes tempest job using lbaasv2
    host-vars:
      controller:
        devstack_plugins:
          neutron-lbaas: https://git.openstack.org/openstack/neutron-lbaas
    vars:
      devstack_localrc:
          NEUTRON_LBAAS_SERVICE_PROVIDERV2: 'LOADBALANCERV2:Haproxy:neutron_lbaas.drivers.haproxy.plugin_driver.HaproxyOnHostPluginDriver:default'
      devstack_services:
        q-lbaasv2: true

- job:
    name: kuryr-kubernetes-tempest-lbaasv2-centos-7
    parent: kuryr-kubernetes-tempest-lbaasv2
    nodeset: openstack-centos-7-single-node
    voting: false

- job:
    name: kuryr-kubernetes-tempest-daemon-lbaasv2
    parent: kuryr-kubernetes-tempest-lbaasv2
    description: |
      Kuryr-Kubernetes tempest job using lbaasv2 and CNI daemon
    vars:
      devstack_services:
        kuryr-daemon: true

- job:
    name: kuryr-kubernetes-tempest-openshift-lbaasv2
    parent: kuryr-kubernetes-tempest-lbaasv2
    description: |
      Kuryr-Kubernetes tempest job using lbaasv2 and OpenShift
    vars:
      devstack_localrc:
        DOCKER_CGROUP_DRIVER: "systemd"
      devstack_services:
        kubernetes-api: false
        kubernetes-controller-manager: false
        kubernetes-scheduler: false
        kubelet: false
        openshift-master: true
        openshift-node: true

- job:
    name: kuryr-kubernetes-tempest-daemon-openshift-lbaasv2
    parent: kuryr-kubernetes-tempest-openshift-lbaasv2
    description: |
      Kuryr-Kubernetes tempest job using lbaasv2, CNI daemon and OpenShift
    vars:
      devstack_services:
        kuryr-daemon: true
    voting: false

- job:
    name: kuryr-kubernetes-tempest-multinode-lbaasv2
    parent: kuryr-kubernetes-tempest-lbaasv2
    description: |
      Kuryr-Kubernetes tempest multinode job using lbaasv2
    nodeset: openstack-two-node
    host-vars:
      controller:
        devstack_plugins:
          devstack-plugin-container: https://git.openstack.org/openstack/devstack-plugin-container
          kuryr-kubernetes: https://git.openstack.org/openstack/kuryr
          neutron-lbaas: https://git.openstack.org/openstack/neutron-lbaas
    group-vars:
      subnode:
        devstack_services:
          c-vol: false
          c-bak: false
          q-lbaasv2: false
          tls-proxy: false
    vars:
      devstack_services:
        tls-proxy: false
    voting: false

- job:
    name: kuryr-kubernetes-tempest-ovn
    parent: kuryr-kubernetes-tempest-octavia
    description: |
        Kuryr-Kubernetes tempest job using OVN
    required-projects:
      - openstack/networking-ovn
    host-vars:
      controller:
        devstack_plugins:
          networking-ovn: https://git.openstack.org/openstack/networking-ovn
          neutron: https://git.openstack.org/openstack/neutron
    vars:
      devstack_localrc:
        OVS_HOST_PATH: /usr/local/var/run/openvswitch
        Q_USE_PROVIDERNET_FOR_PUBLIC: true
        PHYSICAL_NETWORK: public
        OVN_L3_CREATE_PUBLIC_NETWORK: true
      devstack_services:
        ovn-northd: true
        ovn-controller: true
        networking-ovn-metadata-agent: true
        q-agt: false
        q-l3: false
        q-dhcp: false
        q-meta: false
        q-trunk: true
        kuryr-daemon: true
    voting: false

- job:
    name: kuryr-kubernetes-tempest-daemon-ovn
    parent: kuryr-kubernetes-tempest-ovn
    description: |
        Kuryr-Kubernetes tempest job using OVN, CNI daemon
    vars:
      devstack_services:
        kuryr-daemon: true

- job:
    name: kuryr-kubernetes-tempest-daemon-containerized-ovn
    parent: kuryr-kubernetes-tempest-daemon-ovn
    description: |
        Kuryr-Kubernetes tempest job using OVN, CNI daemon and Containerized
    vars:
      devstack_localrc:
        KURYR_K8S_CONTAINERIZED_DEPLOYMENT: true

- job:
    name: kuryr-kubernetes-tempest-dragonflow
    parent: kuryr-kubernetes-tempest-lbaasv2
    description: |
      Kuryr-Kubernetes tempest job using Dragonflow
    required-projects:
      - openstack/dragonflow
    vars:
      devstack_localrc:
        Q_ENABLE_DRAGONFLOW_LOCAL_CONTROLLER: true
        DF_RUNNING_IN_GATE: true
        TUNNEL_TYPE: vxlan
        DF_L2_RESPONDER: true
        OVS_INSTALL_FROM_GIT: false
        OVS_BRANCH: master
      devstack_services:
        q-agt: false
        q-dhcp: false
        q-l3: false
        q-trunk: true
        df-redis: true
        df-redis-server: true
        df-controller: true
        df-ext-services: true
        df-l3-agent: true
      devstack_plugins:
        dragonflow: https://github.com/openstack/dragonflow
    voting: false

- job:
    name: kuryr-kubernetes-tempest-containerized-lbaasv2
    parent: kuryr-kubernetes-tempest-lbaasv2
    description: |
        Tempest with LBaaSV2 and containers
    vars:
      devstack_localrc:
        KURYR_K8S_CONTAINERIZED_DEPLOYMENT: true

- job:
    name: kuryr-kubernetes-tempest-daemon-containerized-lbaasv2
    parent: kuryr-kubernetes-tempest-daemon-lbaasv2
    description: |
        Tempest with LBaaSV2, CNI daemon enabled and containers
    vars:
      devstack_localrc:
        KURYR_K8S_CONTAINERIZED_DEPLOYMENT: true

- job:
    name: kuryr-kubernetes-tempest-daemon-containerized-octavia-namespace
    description: |
      Tempest with Octavia, CNI daemon, containers and namespace subnet driver
    parent: kuryr-kubernetes-tempest-daemon-containerized-octavia
    vars:
      tempest_test_regex: '^(kuryr_tempest_plugin.tests.scenario.test_namespace.TestNamespaceScenario.test_namespace)'
      devstack_localrc:
        KURYR_SUBNET_DRIVER: namespace
        KURYR_ENABLED_HANDLERS: vif,lb,lbaasspec,namespace
    voting: false

- job:
    name: kuryr-kubernetes-tempest-daemon-containerized-openshift-lbaasv2
    description: Tempest with LBaaS v2, CNI daemon enabled, containers and OpenShift
    parent: kuryr-kubernetes-tempest-daemon-openshift-lbaasv2
    vars:
      devstack_localrc:
        KURYR_K8S_CONTAINERIZED_DEPLOYMENT: true
